<!DOCTYPE html>
<html lang="en">

<body>
    <div class="container">
        <div class="row justify-content-center">

            <div class=" mt-5 mb-4 shadow p-3 mb-5 bg-body-tertiary rounded" style="width: 60%;">
                <h4 class=" d-flex justify-content-center">Agregar una habitación</h4>
                <form action="addRoom" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="tamaño">Tamaño</label>
                        <input type="text" name="tamaño" id="tamaño" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripción</label>
                        <input type="text" name="descripcion" id="descripcion" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="imagen" class="form-label">Imagen</label>
                        <input type="file" name="imagen" id="imagen" class="form-control" accept="image/*" required>
                    </div>
                    <div class="form-group">
                        <label for="precio">Precio</label>
                        <input type="number" name="precio" id="precio" class="form-control" required>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mt-2" style="width: 40%;">Agregar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>