<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Hotel & Resort Soria</title>
</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= BASE_URL ?>home">Hotel & Resort Soria</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>rooms">Habitaciones</a>
                    </li>
                    <?php if (isset($_SESSION['USER_ID']) && ($_SESSION['ADMIN'] == 0)) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>listReserves">Mis reservas</a>
                        </li>
                    <?php endif ?>
                    <?php if (isset($_SESSION['USER_ID']) && ($_SESSION['ADMIN'] == 1)) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>listReserves">Mis reservas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>showRooms">Administracion</a>
                        </li>
                    <?php endif ?>
                </ul>
                <form class="d-flex">

                    <?php if (!isset($_SESSION['USER_ID'])) : ?>
                        <button class="btn btn-light" type="submit">
                            <a href="<?= BASE_URL ?>login" style="text-decoration: none; color: black;">Iniciar sesion</a>
                        </button>
                    <?php else : ?>
                        <button class="btn btn-danger " type="submit">
                            <a href="<?= BASE_URL ?>logout" style="text-decoration: none; color: white;">Cerrar sesion (<?= $_SESSION['USER_NAME'] ?>)</a>
                        </button>
                    <?php endif ?>
                </form>
            </div>
        </div>
    </nav>