<?php require 'templates/header.phtml' ?>
<div id="carouselExampleCaptions" class="carousel slide">
	<div class="carousel-indicators">
		<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
		<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
		<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
	</div>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="images/carrusel4.jpg" class="d-block w-100" height="520" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>Admire las vistas de La Mansión y la ciudad desde las ventanas de este amplio y luminoso santuario, que cuenta con un bar privado.</h5>
				<p>SORIA</p>
			</div>
		</div>
		<div class="carousel-item">
			<img src="images/carrusel5.jpg" class="d-block w-100" height="520" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>Reciba invitados en su elegante sala de estar y deléitese con la seleccionada colección de vinos argentinos de su bar privado.</h5>
				<p>SORIA</p>
			</div>
		</div>
		<div class="carousel-item">
			<img src="images/carrusel6.jpg" class="d-block w-100" height="520" alt="...">
			<div class="carousel-caption d-none d-md-block">
				<h5>Situada en La Mansión, esta elegante suite ostenta decoración clásica del Viejo Continente, incluyendo antigüedades originales que evocan la Francia del siglo XVIII. Desde el amplio balcón de la habitación se puede saborear una copa con vistas al jardín.</h5>
				<p>SORIA</p>
			</div>
		</div>
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Previous</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Next</span>
	</button>
</div>
<div class="d-flex  justify-content-center m-3" style="width: 98%;">
	<div class="d-flex  justify-content-center m-3 bg-gray" style="width: 60%;">
		<div>
			<h5 class="d-flex  justify-content-center m-3">ELEGANCIA EUROPEA CON UN TOQUE EXCLUSIVAMENTE ARGENTINO</h5>
			<p class="d-flex  justify-content-center m-3">Ubicado en el exclusivo barrio de La Recoleta, Hotel & resort Soria combina una mansión de principios del siglo XX y una torre contemporánea, lo que resulta en lo mejor de las comodidades modernas con glamur del estilo europeo. Reúnase con colegas y amigos para tomar cócteles en Pony Line y carnes maduradas en seco en Elena, o disfrute de una tradición porteña –la parrillada del domingo– en Nuestro Secreto Restaurante.</p>
		</div>
	</div>
</div>
<div class="d-flex justify-content-center m-3">
	<h3>Promociones y Vouchers seleccionados para usted</h3>
</div>
<div class="d-flex flex-colum">
	<div class="card m-3 shadow-lg" style="width: 18rem;">
		<img src="images/habitacion_cuadruple.jpg " width="200" height="200" class="card-img-top" alt="...">
		<div class="card-body">
			<h5 class="card-title">Mejor tarifa garantizada</h5>
			<p class="card-text">Beneficio por reserva directa web oficial</p>
			<p class="card-text">Descuento 10% OFF</p>
			<a href="rooms" class="btn btn-primary">Ver mas</a>
		</div>
	</div>
	<div class="card m-3 shadow-lg" style="width: 18rem;">
		<img src="images/habitacion_triple.jpg" width="200" height="200" class="card-img-top" alt="...">
		<div class="card-body">
			<h5 class="card-title">Mejor tarifa garantizada</h5>
			<p class="card-text">Beneficio por reserva directa web oficial</p>
			<p class="card-text">Descuento 15% OFF</p>
			<a href="rooms" class="btn btn-primary">Ver mas</a>
		</div>
	</div>
</div>






<?php require 'templates/footer.phtml';
