<?php require 'templates/header.phtml' ?>

<div class=" card d-flex m-5 p-5 flex-column justify-content-center align-items-center bg-white border shadow-lg">
        <h1 class="mb-3">Bienvenidos al Hotel & Resort Soria</h1>
        <h5 class="mb-2">por favor, inicie sesion para crear y comenzar a gestionar sus reservas</h5>
    <form class="mt-5" style="width: 50%;" method="POST" action="auth">
            <label for="nombre">Nombre de usuario</label>
            <input type="nombre" required class="form-control " id="nombre" name="nombre">
            <label for="password">Contraseña</label>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-key" viewBox="0 0 16 16">
            <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z"/>
            <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
            </svg>
            <input type="password" required class="form-control" id="password" name="password">
            <?php if ($error) : ?>
                <div class='alert alert-danger' role='alert'>
                    <?= $error ?>
                </div>
            <?php endif ?>
            <div class="d-flex align-items-center flex-column mb-3">
                <button type="submit" class="btn btn-primary mt-3">Iniciar sesion</button>
            </div>
    </form>
</div>    
<?php require 'templates/footer.phtml' ?>