<?php require 'templates/header.phtml'?>
<h1 class="d-flex align-items-center justify-content-center mt-5">Mis reservas</h1>
    <div class="list-group m-5 p-5">
        <?php foreach($reserves as $reserve) :?>
        <div class="d-flex justify-content-evenly">
            <img width="600" height="300" src="https://www.barcelonairporthotel.com/wp-content/uploads/2023/09/Deluxe-2022-1.jpg" alt="">
            <div class="list-group-item list-group-item-action pt-3">
              <div class="d-flex w-100 justify-content-between mt-4">
                <h3 class="mb-5">Habitacion <?= $reserve->tamaño ?></h3>
                <?php if ($reserve->finalizada === 0) : ?>
                <small class="text-warning" style="font-weight: bold;">PENDIENTE</small>
                <?php else: ?>
                <small class="text-success" style="font-weight: bold;">CONFIRMADA</small>
                <?php endif ?>
                </div>
                <h6 class="mb-3">Paquetes adicionales</h6>
              <ul>
                  <li>Paquete All Inclusive</li>
                  <li>Excursiones guiadas</li>
                </ul>
                <div class="mt-5 d-flex justify-content-between">
                    <small><?= $reserve->cant_noches ?> noches</small>
                    
                    <div class="d-flex">
                        <h5 class="mt-2 mx-3">$<?= $reserve->total ?></h5>
                        <br>
                        <button type="button" class="btn btn-secondary mx-2">
                          <a class="nav-link active" aria-current="page" href="detailreserve/<?= $reserve->id ?>">Ver detalle</a>
                        </button>
                        <?php if ($reserve->finalizada === 0) : ?>
                        <button type="button" class="btn btn-success">
                            <a class="nav-link active" aria-current="page" href="confirmReserveList/<?= $reserve->id ?>">Confirmar</a>
                        </button>
                        <?php endif ?>
                    </div>
                    
                       
                    
                </div>
            </div>
        </div>
        <?php endforeach ?>
      </div>
<?php require 'templates/footer.phtml' ?>